### ISSUE TITLE
Code  confusion  

### ISSUE THREAD

**Issue by zhangbububu** [lliai/DisWOT-CVPR2023#4]
<img width="642" alt="image" src="https://github.com/lilujunai/DisWOT-CVPR2023/assets/41133441/4cd64d84-f00b-4498-836a-023f03f1e195">

t_grad_cam, s_grad_cam  ===>  (n_classes,   d_model) 

and  t_grad_cam, s_grad_cam   are   inputs   of      channel_similarity

so  why we have :
```
    bsz, ch = f_s.shape[0], f_s.shape[1]
    # Reshape
    f_s = f_s.view(bsz, ch, -1)
    f_t = f_t.view(bsz, ch, -1)
```

**Comment by lliai** [comment]
Many thanks for your attention, our full code has been published! If you have any other questions, feel free to reach out by email, thank you!

Best
Lujun
